### ISSUE TITLE
Headless Neo

### ISSUE THREAD

**Issue by ekkis** [neo4j/docker-neo4j#14]
I have an application based on the Linkurious library, which I'm packaging into a Docker image.  it was my hope that I'd be able to run a Neo container without publishing its ports (so the client can't access it) but `--link` the Linkurious container so that all access to the database would be through the app.

seemed reasonable enough until I realized that the app runs on the client browser and thus needs to be able to access Neo directly.

my concern is that users will just navigate to the `/browser` page and issue random queries and mess with data.  so I asked Michael and he suggested that removing the libraries that implement the browser would solve this.  the two files in question are:

> neo4j-browser-2.3.0.jar

and

> neo4j-server-2.3.0-static-web.jar

so whilst I can create a new image based on the official issued by Neo, I think a slight enhancement to the existing image would be better, since this is a very common requirement.

ideally I'd like to pass a `--headless` when running the Neo container, or maybe through an environment variable:

    --env NEOJ_NO_BROWSER=true

á la NO_AUTH

thoughts?

**Comment by benbc** [comment]
@ekkis Hello. Thanks for this request. We've discussed it and come up with three alternatives that would allow you to achieve this without modifying the Neo4j container.

1. Write a [security rule](http://neo4j.com/docs/stable/security-server.html#_server_authorization_rules) which denies access to `/browser/` URIs.
1. Put a reverse proxy in an other container in front of the database and use it to deny access to `/browser/` URIs.
1. Modify a [hidden configuration option](https://github.com/neo4j/neo4j/blob/3.0/community/server/src/main/java/org/neo4j/server/web/ServerInternalSettings.java#L71) to change the URI prefix for the browser.

Will any of those do what you need?

**Comment by ekkis** [comment]
I don't think option #3 is viable as someone could guess (or write a script to test the combinations) what the new prefix is.

#1 seems like a good approach but rather than my writing it, it would be better if it could be part of the neo package, since it involves writing code.  perhaps we could discuss how exactly this can happen (are you on slack?)

#2 is also feasible but seems like a lot of overhead for a very simple requirement.  it requires much more knowledge for someone wanting to run a headless neo instance in terms of how proxies work and need to be configured

**Comment by ekkis** [comment]
honestly using the aforementioned environment variable would be much better because it means that one can turn off the functionality at runtime.  so the Docker image doesn't even need to be modified because it just passes the value through to the about-to-be-run Neo4j server, which does the right thing

**Comment by benbc** [comment]
@ekkis I've discussed this with our product management team. They are reviewing the way the browser is packaged with the product and this may change in Neo4j 3.0 in a way that allows you to disable the browser altogether. I've added your voice in favour of that.

We don't want to implement product-level features like this in the Docker image only because it will cause maintenance and compatibility problems and because users of other package types will not benefit.

So I'm afraid that if you need this functionality now, you are going to have to implement it yourself.

As we discussed on Slack, I think that the security rule is the "right" way to do this. The rule can be deployed into the Neo4j container using the existing configuration and extension-mounting mechanisms. If you need help writing the rule then I recommend StackOverflow as a great place to get Neo4j advice.

The other options are also viable, though, so you have alternatives if you don't want to write code.

I'm going to close this issue now, but please reopen it if you have problems with the Docker-related aspects of the implementation.
