### ISSUE TITLE
entrypoint is making files and folders world writable and executable

### ISSUE THREAD

**Issue by rweverwijk** [neo4j/docker-neo4j#164]
Hi All,

Both Dockerfile and the docker-entrypoint.sh are changing the rights of a some folders recursively. This is giving some unwanted security risks.

There is no reason to permit the world write and execute access to `/data` or `/logs` and all it's files.

My suggestion would be to change the access in the docker file to:

- 700 for `/data` and sub directories (read not the files)
- 700 for `/data/databases`
- 755 for `/logs`
- 700 for `${NEO4J_HOME}` or by extracting the tar with `--same-owner` the permissions are set as the package.

I would also argue that the docker-entrypoint should not change permissions at all. The base image is correct. If people mount directories they should be able to control them.

Cheers,
Ron

**Comment by moxious** [comment]
Related - users have previously reported some permission denied errors in various combinations, when a host volume is mapped to /data -- in these cases, the docker container is trying to change permissions on a host-owned directory, which may be owned/controlled by a user other than the user running the docker executable.

**Comment by rweverwijk** [comment]
Extra on this: we would like to control the /data/dbms with kubernetes secrets. 

Binding a secret as directory makes it readonly. The recursive `chown` and `chmod` fail for this reason.

**Comment by jennyowen** [comment]
Permissions on mounted folders are a reoccurring problem with our docker images (and docker in general).
By default, Neo4j runs as the user `neo4j` (because https://github.com/neo4j/docker-neo4j/issues/50), who only exists in the container, not on the host. That means that it's hard to set up folders on the host, which this new user has permissions for.

This is quite a complicated issue, and it's hard to fix file permissions in a way that won't also break backwards compatibility for other users.

There's some discussion of that here:
https://github.com/neo4j/docker-neo4j/pull/161

You can use the `--user` flag on docker run to specify which user to run neo4j as. If you use a user that has write access to your data/log/conf folders then folder ownership is not changed. Note that the `--user` flag to docker is the user the container will run stuff as **inside the container** (see: https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate). This means if you specify a host user name, docker won't recognise it as having write access to your folder. You need to specify the **user ID**. As an example, you can do `--user="$(id -u)":"$(id -g)"` to specify the current user. 
This is a docker limitation and there's not much we can do about it.

Another alternative is to mount docker volumes (instead of host folders) to your container. For example:
```
docker volume create --name neo4jdata
docker volume create --name neo4jlogs
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume neo4jdata:/data --volume neo4jlogs:/logs \
    neo4j:latest
```

This would persist log and data information between containers, since your data would be stored in the docker volume.


I realise the current behaviour of Neo4j docker is not good. I'm hoping to be able to do an overhaul of the docker code for the next minor release, and fix these persistent file permissions problems.

#130 
#131

**Comment by jennyowen** [comment]
Related issues:
#130 
#131

**Comment by rweverwijk** [comment]
> This is quite a complicated issue, and it's hard to fix file permissions in a way that won't also break backwards compatibility for other users.

That's a true point.

There is a great flexibility in running docker containers. With plain docker, docker with custom mounting points, with kubernetes and the list continues.

It is indeed very complex to find a solution for all these differences. The best way to support al these differences is by keeping things simple.

Check if the directories are writable by the user starting Neo4j, give proper messages if they don't.
Let the user providing the filesystem provide access, instead of taking the ownership and permissions on the host system from within the docker container.

I'm working on a PR with a setup of this, would love to have your feedback on this, this should be ready today.

Cheers,
Ron
