### ISSUE TITLE
Invalid option docker run

### ISSUE THREAD

**Issue by MatthewDavidYoung** [neo4j/docker-neo4j#19]
Using Docker 1.9.1 on Windows 8 and pulled down the latest docker-neo4j repo

Ran a Docker build from the 2.3.1 directory using the tag **neo4j/neo4j**.  Tried running with STDIN back:
     
     docker run -i -t --rm -p 7474:7474 -v //d/<path to data>:/data --name graphdb neo4j/neo4j

Every time I get _": invalid option"_.  Not sure if I am missing an argument after the image?  Note, that the volume to the image's _data_ directory on my Windows machine is empty.  Wondering if I am doing a rookie mistake with Docker or just missing something fundamental when try to run the neo4j image?

**Comment by benbc** [comment]
@MatthewDavidYoung Are you using Docker Toolbox?

I'm not sure about the intricacies of running Docker on Windows. One thing I suspect is that the path you specify on the host side for the volume needs to be under `c:\Users\<your-user>` in order for it to be automatically mounted into the Docker host VM.

Can I suggest that you try this with a simple, standard Docker image (e.g. `hello-world` or `debian`) so that we can see if it's a problem with the Neo4j image or the command line arguments that you're providing?

**Comment by MatthewDavidYoung** [comment]
@benbc Thanks!  Newbee to both Docker and VirtualBox.  Didn't realize that volumes from the outside world on Windows have to reside under the C:/Users/<user> directory.  Is this a Docker thing or VirtualBox thing?

**Comment by benbc** [comment]
@MatthewDavidYoung It's due to the way Docker is set up to work on Windows. Details [here](http://docs.docker.com/engine/installation/windows/).
