### ISSUE TITLE
Can not use the same data directory for different containers?

### ISSUE THREAD

**Issue by MrRace** [neo4j/docker-neo4j#215]
I create two containers named "neo4j_1" and  "neo4j_2". For the "neo4j_1"  I  map  the data directory with the "-v"  parameter.The whole command is：
```
docker run --name=neo4j_1  -it -p 7473:7473 -p 7474:7474 -p 7687:7687 -v mypath/conf_1:/conf -v mypath/data:/data -d neo4j
```

For the "neo4j_2", I create it with the command below：
``` 
docker run --name=neo4j_2  -it -p 7483:7483 -p 7484:7484 -p 7688:7688 -v mypath/conf_2:/conf -v mypath/data:/data -d neo4j
```
I find that  the "neo4j_1" can run normally, when it comes to start "neo4j_2", it goes wrong. I think maybe the `data/databases/store_lock`  file restrain the sharing. Therefore I stop the "neo4j_1" and try to start the "neo4j_2" again, but it still fail to start. Why?  I already stop the "neo4j_1" and It should be freely accessible now. What prohibit it ? In my opinion or perceptual intuition, it seems to be feasible. Yup, I can use a different `data` directory for "neo4j_2" to let it start successfully. I come to ask for the principles and settings behind it. Thanks a lot!

**Comment by jennyowen** [comment]
> I think maybe the data/databases/store_lock file restrain the sharing.

yes the `store_lock` file exists to prevent two separate neo4j processes from writing to the same data folder at the same time.

> I stop the "neo4j_1" and try to start the "neo4j_2" again, but it still fail to start. Why?

The expected behaviour is what you expect; that you should be able to use the `/data` directory if there's nothing already using that directory. 

I'm guessing you got a store_lock error, which is pretty common with Neo4j. Usually it means that the last Neo4j process didn't close down cleanly or you still have a neo4j docker container running detached. 
See this stack overflow for steps to fix it: https://stackoverflow.com/a/28587386/11334268
