### ISSUE TITLE
Can't connect to docker 4.0.0 on Windows

### ISSUE THREAD

**Issue by hiiwave** [neo4j/docker-neo4j#230]
Hi, I just installed neo4j 4.0.0 using docker on Windows 10. However, I cannot connect to the web interface via `localhost:7474`.

- Neo4j image tag being used: `neo4j:latest`
- The output of the `docker version` command
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- Operating system: Windows 10
- **Steps to reproduce**

1. Open powershell, and Run docker image
```
PS C:\Users\hiiwa_000\resources> docker run neo4j
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-02-17 17:42:29.594+0000 INFO  ======== Neo4j 4.0.0 ========
2020-02-17 17:42:29.608+0000 INFO  Starting...
2020-02-17 17:42:41.577+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-02-17 17:42:41.578+0000 INFO  Started.
2020-02-17 17:42:42.865+0000 INFO  Remote interface available at http://0.0.0.0:7474/
```
2. Open browser, go to http://localhost:7474/
3. Get **Unable to Connect**

As I am not familiar to docker. Please let me know if I did it wrong.

**Comment by bfeshti** [comment]
Hi @hiiwave, in order to access the neo4j browser from your browser you need to expose the http and bolt ports (7474,7687) to the outside world.
This can be made by running `docker run -p 7474:7474 -p 7687:7687 neo4j` , however you still wont be able to login because you have to use an https port for that (7473) and in the last neo4j version (4.0.0) you need to use your own key and certificate to enable encryption.
Given that,you have 2 possibilities to make it work:
1. Follow the documentation and provide your own key and certificate to enable encryption - https://neo4j.com/docs/operations-manual/current/docker/
2. Use an older version of neo4j that will work out of the box i.e. `docker run -p 7474:7474 -p 7687:7687  neo4j:3.5`

**Comment by hiiwave** [comment]
@bfeshti Thank you so much for the info. I will try it soon.
