### ISSUE TITLE
Improve documentation about password and NEO4J_AUTH

### ISSUE THREAD

**Issue by laurentS** [neo4j/docker-neo4j#231]
- Neo4j image: 3.5.14
- docker version 19.03.5
- Linux

I've just spent half a day trying to figure out why my password set via `NEO4J_AUTH` on my docker image was working fine in my test setup, and not on my production server (I kept getting `neobolt.exceptions.AuthError: The client is unauthorized due to authentication failure` when connecting from a python app using `neobolt`.)

It turns out that the difference is my persistent data volume on the main server, which keeps the password set previously. This is far from obvious when reading [the docs](https://neo4j.com/docs/operations-manual/current/docker/introduction/#docker-volumes). My understanding of this short passage was that setting the environment variable would update the password for the `neo4j` user no matter what.

I found the solution to my problem in [this stackoverflow post](https://stackoverflow.com/q/55152286/1138710).

I think it would be worth expanding a little on how the docker image works with respect to auth when using persistent data volumes (which is a pretty common situation for a database :smile:  ).

**Comment by dcsan** [comment]
I am still having this issue. can't even get started with neo4j.
your linked fix didn't work for me.

**Comment by jennyowen** [comment]
@laurentS yes, the documentation for authentication in Neo4j docker could be better.
I've updated the documentation, but it's not yet been published on the main documentation page. It will definitely be published by the time we do a 4.0.2 release.

I modified the documentation section about `NEO4J_AUTH` a little bit, and also added this statement:

> If you have mounted a /data volume containing an existing database, setting NEO4J_AUTH will have no effect. The Neo4j Docker service will start, but to log in you will need a username and password already associated with the database.


The `NEO4J_AUTH` environment variable will only set the **initial** database password. It won't cause a password change on the underlying database. It would probably be a big security hole if you could do that, since you would be able to set a new password without providing any kind of proof that you knew the old password.

**Comment by laurentS** [comment]
Thanks for clarifying this @jennyowen !
