### ISSUE TITLE
Cannot import graph-data-science plugin

### ISSUE THREAD

**Issue by 2514millerj** [neo4j/docker-neo4j#247]
I want to start a Docker container with the "graph-data-science" plugin. I am running the following command:

```
docker run --publish=7474:7474 --publish=7687:7687 --rm --env NEO4JLABS_PLUGINS='["graph-data-science"]' neo4j:3.5.17
```

which generates this error output:
```
Fetching versions.json for Plugin 'graph-data-science' from 
Error: No jar URL found for version '3.5.17' in versions.json from ''
```

Setting the NEO4JLABS_PLUGINS variable works for the other plugins found at https://github.com/neo4j/docker-neo4j/blob/master/neo4jlabs-plugins.json. What am I missing?

**Comment by jennyowen** [comment]
@2514millerj It doesn't work because the `graph-data-science` plugin integration is a very recent change, and we haven't released a Neo4j image with that update yet.
Since you're running the 3.5.17 image, this is the neo4jlabs-plugins.json you're actually using: https://github.com/neo4j/docker-neo4j/blob/neo4j-3.5.17/neo4jlabs-plugins.json

There should be a 4.0.4 release very soon which will have the change, after which your command will work. I don't know when we're planning on doing the 3.5.18 release.

Meanwhile you can work around this by mounting a folder containing all your plugins to `/plugins` on the container:
https://neo4j.com/docs/operations-manual/current/docker/operations/#docker-procedures

**Comment by 2514millerj** [comment]
Thank you, that makes sense. Did not realize this plugin was so recently added.
