### ISSUE TITLE
2.1.8 => 2.3.1 upgrade failure

### ISSUE THREAD

**Issue by benbc** [neo4j/docker-neo4j#26]
Originally reported by `davisd` in the `neo4j-users` Slack #help-install channel.

Create a new AWS EC2 instance with Amazon linux

```
sudo yum install docker
sudo service docker start
sudo mkdir -p /data/neo4j
sudo chown ec2-user /data/neo4j
sudo -E docker run -i -t -d --name neo4j --privileged -v /data/neo4j:/var/lib/neo4j/data -p 7474:7474 vinelab/neo4j:2.1.8
```

Connect via the browser, create some data

```
sudo docker stop neo4j
sudo docker rm neo4j
sudo docker run --rm  --volume=$HOME/neo4j/conf:/conf neo4j dump-config
```

Edit the neo4j.properties under `~/neo4j/conf` to allow upgrades

```
sudo docker run --detach --publish=7474:7474 --volume=/data/neo4j:/data --volume=$HOME/neo4j/conf:/conf --env=NEO4J_AUTH=none --ulimit=nofile=40000:40000 --name neo4j neo4j
sudo docker logs neo4j
```

You'll get a big stack trace, ultimately this is the issue:

```
Caused by: org.neo4j.kernel.impl.storemigration.StoreUpgrader$UnexpectedUpgradingStoreVersionException: '/var/lib/neo4j/data/graph.db/neostore.nodestore.db' has a store version number that we cannot upgrade from. Expected 'v0.A.3' but file is version ''.

**Comment by domdavis** [comment]
Further investigation may point to the way the DB is being shut down within docker:

* `2.1.8` running directly on the box -> `2.3.1` running directly on the box works fine
* `2.1.8` running in docker -> `2.3.1` running directly on the box errors

However, if you go `2.1.8` in Docker, then run `2.1.8` locally against that DB you get the following in the logs:

```
Detected incorrectly shut down database, performing recovery..
```

Running `2.3.1` locally now works fine, as does running it in Docker.

I suspect the issue is that `docker stop` (in the `vinelab` image at the very least) isn't shutting down Neo4j in a nice way which is leaving the DB in a state where it can't be upgraded.

**Comment by domdavis** [comment]
Now I've got a workaround on this it's no longer a blocker for me.

**Comment by benbc** [comment]
@domdavis Ah! Well spotted -- I should have thought of that.

There is a change in Neo4j 2.3.0 which allows Docker to shut it down cleanly. All earlier versions of Neo4j have a problem where Docker has to kill them at shutdown. I wasn't aware that this would cause a problem with upgrades, but I'm sure it's what you're seeing.

We don't support running Neo4j under Docker before 2.3.0. I recommend that you use the latest official image, `neo4j`.

I'm going to close this now, on that basis. Please let me know if you have any more questions.
