### ISSUE TITLE
Neo4j docker image is downloading plugins every time from AWS

### ISSUE THREAD

**Issue by fssrepository** [neo4j/docker-neo4j#304]
While pulling out plugins in your scripts, based on NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]' param, you need to check whether offline version is available with the same version!
Nobody noticed that Terabytes of traffic has been generated on AWS unnecessarily!

In restricted environment this solution is not even working, like behind a load balancer, just with extra costs!

**Comment by jennyowen** [comment]
It is possible to load plugins offline so that you're not downloading so much. Maybe it could be better documented though.

You can use `NEO4JLABS_PLUGINS` to download the correct plugin versions by doing:

```
mkdir -p $HOME/neo4j/plugins 

docker run -it --rm \
--publish=7474:7474 --publish=7687:7687 \
--volume=$HOME/neo4j/plugins:/plugins \
--user="$(id -u):$(id -g)" \
-e NEO4J_AUTH=none \
-e NEO4JLABS_PLUGINS='["apoc","graph-data-science"]' \
neo4j:latest
```

That'll download plugins to `$HOME/neo4j/plugins` on the host. Then next time you run the container, skip the `NEO4JLABS_PLUGINS` environment variable:

```
docker run -it --rm \
--publish=7474:7474 --publish=7687:7687 \
--volume=$HOME/neo4j/plugins:/plugins \
--user="$(id -u):$(id -g)" \
-e NEO4J_AUTH=none \
neo4j:latest
```

and you'll have a neo4j container with all the plugins you wanted without re-downloading anything.

**Comment by EarthlingDavey** [comment]
@fssrepository hey I got a nice hack for you my boyo... 

See how the plugins are handled in this project. Namely a custom Dockerfile is used with `FROM neo4j` and 

```
ENV APOC_VERSION=4.2.0.2
ENV APOC_URI https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/${APOC_VERSION}/apoc-${APOC_VERSION}-all.jar
RUN sh -c 'cd /var/lib/neo4j/plugins && curl -L -O "${APOC_URI}"'
```
