### ISSUE TITLE
Neo4j 4.4 not available on hub.docker.com

### ISSUE THREAD

**Issue by motey** [neo4j/docker-neo4j#321]
is the pipeline broken or is there a deliberate delay for publishing neo4j 4.4. on dockerhub?

https://hub.docker.com/_/neo4j?tab=tags
Cheers

**Comment by jennyowen** [comment]
@motey I have to create a github PR for docker to accept the new release in dockerhub, but because we're trying to introduce ARM64 images this time it's taking a little longer than it normally does.
The relevant PR to follow is https://github.com/docker-library/official-images/pull/11432

If you want to get the images anyway from the non-official channel, I did push the 4.4.0 image to our experimental repo:
`neo4j/neo4j-experimental:4.4.0`
and 
`neo4j/neo4j-experimental:4.4.0-enterprise`
