### ISSUE TITLE
Neo4j Graph Data Science plugin not specified for v3.5.35

### ISSUE THREAD

**Issue by jacob-ablowitz** [neo4j/docker-neo4j#384]
The plugins json map at https://graphdatascience.ninja/versions.json only supports as high as v3.5.33 but the latest v3.5 container is v3.5.35 so anyone attempting to use v3.5.35 with graph-data-science can't start their containers. This is directly affecting my e2e testing right now.

**Comment by Mats-SX** [comment]
Hello @jacob-ablowitz and thanks for raising this issue.

Neo4j 3.5 is officially end of life since May this year (see [this page](https://neo4j.com/developer/kb/neo4j-supported-versions/) for a reference of official EOL dates). We do not recommend using it.

Similarly, GDS version 1.1 was kept alive for the sole purpose of Neo4j 3.5 compatibility, but it also went EOL following the EOL of Neo4j 3.5. As such, there is no GDS version that we officially support for Neo4j 3.5.

If you have an active commercial engagement with Neo4j, I recommend that you contact our Customer Success or Customer Support organisations, to which you should have contact information shared through the commercial engagement. 
If you are currently relying on the Community Edition of Neo4j, then the best option for you would be to migrate to Neo4j 4.4, for which the supported GDS version would be GDS 2.2.0 which we released just this week.

I hope this helps
All the best
Mats
