### ISSUE TITLE
Is there a way to switch databases from within Cypher?

### ISSUE THREAD

**Issue by vielmetti** [neo4j/docker-neo4j#51]
I've been experimenting with the provided "graph.db" inside the Docker instance for neo4j, and I'd now like to abandon everything I've done and start over. The obvious thing to do would seem to be to create a new database, point the console at it, and keep going. It's not clear to me how that would be done, though, even after looking at the documentation.

I think I can accomplish the same goal by killing my Docker container and then restarting it pointing at a new data directory, but it would seem to make more sense somehow if there was a better way than that, ideally a set of commands within Cypher.

thanks for any hints!

**Comment by benbc** [comment]
@vielmetti There is no way to do operations like this through Cypher or on a running database generally. There are plans to add this soft of thing to Neo4j at some point but there is no firm timescale yet.

Since Docker containers are inherently ephemeral, in your case I would definitely just kill the container and start a new one.
